### ISSUE TITLE
Duplicated import

### ISSUE THREAD

**Issue by luckybusted** [unicornwitnesses/unicornwitnesses-new#4]
https://github.com/unicornwitnesses/unicornwitnesses-new/blob/13ddd31356d4c4b52b7a9b320e54239cd1eee926/src/scss/header.scss#L2

Duplicated import of `colors.scss` and `mixins.scss` because the files already imported into the `style.scss`.
Can be removed.

**Comment by HakasLepehen** [comment]
fixed
